[2024-06-28T03:44:17.323+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-28T03:44:17.334+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: amazon_analytics_dag.tsk_is_file_in_s3_available manual__2024-06-28T03:44:03.710206+00:00 [queued]>
[2024-06-28T03:44:17.341+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: amazon_analytics_dag.tsk_is_file_in_s3_available manual__2024-06-28T03:44:03.710206+00:00 [queued]>
[2024-06-28T03:44:17.341+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 3
[2024-06-28T03:44:17.370+0000] {taskinstance.py:2330} INFO - Executing <Task(S3KeySensor): tsk_is_file_in_s3_available> on 2024-06-28 03:44:03.710206+00:00
[2024-06-28T03:44:17.376+0000] {standard_task_runner.py:63} INFO - Started process 36414 to run task
[2024-06-28T03:44:17.380+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'amazon_analytics_dag', 'tsk_is_file_in_s3_available', 'manual__2024-06-28T03:44:03.710206+00:00', '--job-id', '90', '--raw', '--subdir', 'DAGS_FOLDER/amazonanalytics.py', '--cfg-path', '/tmp/tmpyl344i9t']
[2024-06-28T03:44:17.381+0000] {standard_task_runner.py:91} INFO - Job 90: Subtask tsk_is_file_in_s3_available
[2024-06-28T03:44:17.421+0000] {task_command.py:426} INFO - Running <TaskInstance: amazon_analytics_dag.tsk_is_file_in_s3_available manual__2024-06-28T03:44:03.710206+00:00 [running]> on host ip-172-31-19-147.us-west-2.compute.internal
[2024-06-28T03:44:17.499+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='myemail@domain.com' AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='amazon_analytics_dag' AIRFLOW_CTX_TASK_ID='tsk_is_file_in_s3_available' AIRFLOW_CTX_EXECUTION_DATE='2024-06-28T03:44:03.710206+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-28T03:44:03.710206+00:00'
[2024-06-28T03:44:17.499+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-28T03:44:17.512+0000] {baseoperator.py:400} WARNING - S3KeySensor.execute cannot be called outside TaskInstance!
[2024-06-28T03:44:17.512+0000] {s3.py:117} INFO - Poking for key : s3://cleaned-data-zone-csv-bucket5/response_data_28062024034406.csv
[2024-06-28T03:44:17.518+0000] {base.py:84} INFO - Using connection ID 'aws_s3_conn' for task execution.
[2024-06-28T03:44:17.518+0000] {connection_wrapper.py:384} INFO - AWS Connection (conn_id='aws_s3_conn', conn_type='aws') credentials retrieved from login and password.
[2024-06-28T03:44:22.993+0000] {s3.py:117} INFO - Poking for key : s3://cleaned-data-zone-csv-bucket5/response_data_28062024034406.csv
[2024-06-28T03:44:28.002+0000] {s3.py:117} INFO - Poking for key : s3://cleaned-data-zone-csv-bucket5/response_data_28062024034406.csv
[2024-06-28T03:44:28.028+0000] {base.py:294} INFO - Success criteria met. Exiting.
[2024-06-28T03:44:28.028+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-28T03:44:28.033+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=amazon_analytics_dag, task_id=tsk_is_file_in_s3_available, run_id=manual__2024-06-28T03:44:03.710206+00:00, execution_date=20240628T034403, start_date=20240628T034417, end_date=20240628T034428
[2024-06-28T03:44:28.053+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-28T03:44:28.062+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-28T03:44:28.063+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
