[2024-06-26T23:02:29.831+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-26T23:02:29.852+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: amazon_analytics_dag.tsk_extract_amazon_data_var scheduled__2024-06-25T00:00:00+00:00 [queued]>
[2024-06-26T23:02:29.857+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: amazon_analytics_dag.tsk_extract_amazon_data_var scheduled__2024-06-25T00:00:00+00:00 [queued]>
[2024-06-26T23:02:29.858+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 3
[2024-06-26T23:02:29.875+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): tsk_extract_amazon_data_var> on 2024-06-25 00:00:00+00:00
[2024-06-26T23:02:29.880+0000] {standard_task_runner.py:63} INFO - Started process 26977 to run task
[2024-06-26T23:02:29.883+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'amazon_analytics_dag', 'tsk_extract_amazon_data_var', 'scheduled__2024-06-25T00:00:00+00:00', '--job-id', '11', '--raw', '--subdir', 'DAGS_FOLDER/amazonanalytics.py', '--cfg-path', '/tmp/tmp1j6x2jw4']
[2024-06-26T23:02:29.884+0000] {standard_task_runner.py:91} INFO - Job 11: Subtask tsk_extract_amazon_data_var
[2024-06-26T23:02:29.926+0000] {task_command.py:426} INFO - Running <TaskInstance: amazon_analytics_dag.tsk_extract_amazon_data_var scheduled__2024-06-25T00:00:00+00:00 [running]> on host ip-172-31-19-147.us-west-2.compute.internal
[2024-06-26T23:02:29.996+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='myemail@domain.com' AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='amazon_analytics_dag' AIRFLOW_CTX_TASK_ID='tsk_extract_amazon_data_var' AIRFLOW_CTX_EXECUTION_DATE='2024-06-25T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-25T00:00:00+00:00'
[2024-06-26T23:02:29.996+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-26T23:02:30.011+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-26T23:02:30.011+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/ubuntu/deevar_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/deevar_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/deevar_venv/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/deevar_venv/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/deevar_venv/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/airflow/dags/amazonanalytics.py", line 21, in extract_amazon_data
    response = requests.get(url, headers=headers, params=querystring)
               ^^^^^^^^
NameError: name 'requests' is not defined
[2024-06-26T23:02:30.019+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=amazon_analytics_dag, task_id=tsk_extract_amazon_data_var, run_id=scheduled__2024-06-25T00:00:00+00:00, execution_date=20240625T000000, start_date=20240626T230229, end_date=20240626T230230
[2024-06-26T23:02:30.033+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 11 for task tsk_extract_amazon_data_var (name 'requests' is not defined; 26977)
[2024-06-26T23:02:30.055+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-26T23:02:30.067+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-26T23:02:30.068+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
