[2024-06-26T23:02:50.310+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-26T23:02:50.331+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: amazon_analytics_dag.tsk_extract_amazon_data_var manual__2024-06-26T23:02:09.225610+00:00 [queued]>
[2024-06-26T23:02:50.337+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: amazon_analytics_dag.tsk_extract_amazon_data_var manual__2024-06-26T23:02:09.225610+00:00 [queued]>
[2024-06-26T23:02:50.337+0000] {taskinstance.py:2306} INFO - Starting attempt 3 of 3
[2024-06-26T23:02:50.353+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): tsk_extract_amazon_data_var> on 2024-06-26 23:02:09.225610+00:00
[2024-06-26T23:02:50.358+0000] {standard_task_runner.py:63} INFO - Started process 26983 to run task
[2024-06-26T23:02:50.361+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'amazon_analytics_dag', 'tsk_extract_amazon_data_var', 'manual__2024-06-26T23:02:09.225610+00:00', '--job-id', '14', '--raw', '--subdir', 'DAGS_FOLDER/amazonanalytics.py', '--cfg-path', '/tmp/tmpe3tx81vi']
[2024-06-26T23:02:50.363+0000] {standard_task_runner.py:91} INFO - Job 14: Subtask tsk_extract_amazon_data_var
[2024-06-26T23:02:50.403+0000] {task_command.py:426} INFO - Running <TaskInstance: amazon_analytics_dag.tsk_extract_amazon_data_var manual__2024-06-26T23:02:09.225610+00:00 [running]> on host ip-172-31-19-147.us-west-2.compute.internal
[2024-06-26T23:02:50.475+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='myemail@domain.com' AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='amazon_analytics_dag' AIRFLOW_CTX_TASK_ID='tsk_extract_amazon_data_var' AIRFLOW_CTX_EXECUTION_DATE='2024-06-26T23:02:09.225610+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-26T23:02:09.225610+00:00'
[2024-06-26T23:02:50.475+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-26T23:02:50.489+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-26T23:02:50.489+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/ubuntu/deevar_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/deevar_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/deevar_venv/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/deevar_venv/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/deevar_venv/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/airflow/dags/amazonanalytics.py", line 21, in extract_amazon_data
    response = requests.get(url, headers=headers, params=querystring)
               ^^^^^^^^
NameError: name 'requests' is not defined
[2024-06-26T23:02:50.497+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=amazon_analytics_dag, task_id=tsk_extract_amazon_data_var, run_id=manual__2024-06-26T23:02:09.225610+00:00, execution_date=20240626T230209, start_date=20240626T230250, end_date=20240626T230250
[2024-06-26T23:02:50.510+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 14 for task tsk_extract_amazon_data_var (name 'requests' is not defined; 26983)
[2024-06-26T23:02:50.533+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-26T23:02:50.545+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-26T23:02:50.546+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
